GINE: false
base_model: GIN_Custom
dropout: 0
hidden_channels: 64
jk: null
num_layers: 2
num_neighbors:
- 25
- 10
overwrite:
  framework: transductive
  lr: 0.001
  sample_when_predict: true
  sampling_strategy: SAGE
  weight_decay: 0.001
register_info:
  description: Benchmark GIN model.
  tags:
    GINE: false
skip_connection: true
